name: 'coverage'
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    coverage:
        permissions:
          checks: write
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
