# this workflow builds and deploys a container to azure

name: deploy

on: 
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build . --file Dockerfile --tag heorvcc.azurecr.io/heor-markov-api:$(date +%s)
    - uses: Azure/docker-login@v1
      with:
        username: ${{secrets.CONTAINER_REGISTRY_USERNAME}}
        password: ${{secrets.CONTAINER_REGISTRY_PASSWORD}}
        login-server: ${{secrets.CONTAINER_REGISTRY_LOGIN_URL}}
    - run: docker push heorvcc.azurecr.io/heor-markov-api:$(date +%s)