# This is a basic workflow to help you get started with Actions

name: deploy-heroku

# Controls when the workflow will run
on: 
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: CI
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
      uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web
